FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    librdkafka-dev \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*
    
COPY orders.json .

WORKDIR /app
